Run fsck -fy instead of fsck -y

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -47,7 +47,7 @@ echo -n "Mounting filesystems..."
 
 # Mount /. If it fails run a fsck.
 if [ ! "$PLATFORM" = "cdrom" ] ; then
-	/sbin/mount -uw / || (/sbin/fsck -y; /sbin/mount -uw /)
+	/sbin/mount -uw / || (/sbin/fsck -fy; /sbin/mount -uw /)
 
 	# If /conf is a directory, convert it to a symlink
 	# to /cf/conf
@@ -58,10 +58,10 @@ if [ ! "$PLATFORM" = "cdrom" ] ; then
 fi
 
 # Check to see if a compact flash mountpoint exists
-# If it fails to mount then run a fsck -y
+# If it fails to mount then run a fsck -fy
 if grep -q cf /etc/fstab; then
     /sbin/mount -uw /cf || \
-	(/sbin/umount /cf; /sbin/fsck -y /cf; /sbin/mount -w /cf)
+	(/sbin/umount /cf; /sbin/fsck -fy /cf; /sbin/mount -w /cf)
 fi
 
 if [ "$PLATFORM" = "cdrom" ] ; then
